Condition parser
riftgarret/ludum pull request #47
Opened 2018-10-30 01:13 UTC by riftgarret

TLDR: Unified condition logic and parsing with some helper classes and tests. Nothing integrated into the current engine at this time.

## CONDITION LOGIC
(see more at) [The wiki](https://github.com/riftgarret/ludum/wiki/condition-overview)

In addition to this PR:
* added a helper class for building regex called **RegexPatternBuilder**. This helps me read the regex and build the patterns for better optimized parsing.

2018-10-31 19:34 UTC, RiceGnat requested changes

2018-10-31 19:34 UTC, RiceGnat commented on Redninja/Components/Conditions/IExpression.cs
> +		IChainedExpression ChainedExpression { get; }
This seems really weird, is there a good reason for `IExpression` to have a property of type that derives from itself?

2018-10-31 19:34 UTC, RiceGnat commented on Redninja/Components/Conditions/Expressions/ExpressionResolver.cs
> +	public class ExpressionResolver
I think this can be an `internal` class with `public` methods

2018-10-31 19:34 UTC, RiceGnat commented on Redninja/Components/Conditions/Expressions/IValueExpression.cs
> +		object Result { get; }
I'd recommend adding a `T GetResult<T>()` function here. In most cases the compiler should be able to infer `T` so we should be able to type simply `.GetResult()`.

2018-10-31 19:34 UTC, RiceGnat commented on Redninja/Components/Conditions/ResultDefFactory.cs
> +					throw new InvalidProgramException($"Missing implementation for resultType: {resultType}");
use `InvalidOperationException`

2018-10-31 19:34 UTC, RiceGnat commented on Redninja/Data/Schema/Readers/ConditionOpParser.cs
> +					return true;
should this return `false`?

2018-10-31 19:34 UTC, RiceGnat commented on Redninja/Components/Conditions/EventCondition.cs
> +			ExpressionResolver resolver = new ExpressionResolver(self, target, battleModel, battleEvent);
Is `ExpressionResolver` null-safe for the `target` parameter?

2018-11-01 01:45 UTC, riftgarret commented on Redninja/Components/Conditions/IExpression.cs
> +		IChainedExpression ChainedExpression { get; }
This association represents the transition from one expression to another such as `TARGET.HP`, where the `TARGET` connects to the next part of the expression. And the **IChainedExpression** infers that this expression is an expression that requires a parameter from the previous expression. 

Part of this is to create a type of linked list notation from one to the next but we are specifying that only certain types can be linked instead of every type.

2018-11-01 01:45 UTC, riftgarret commented on Redninja/Components/Conditions/Expressions/IValueExpression.cs
> +		object Result { get; }
Ill see what i can get done on the plane, this will most likely be doable without too much fuss

2018-11-01 01:46 UTC, riftgarret commented on Redninja/Data/Schema/Readers/ConditionOpParser.cs
> +					return true;
yep

2018-11-01 01:48 UTC, riftgarret commented on Redninja/Components/Conditions/EventCondition.cs
> +			ExpressionResolver resolver = new ExpressionResolver(self, target, battleModel, battleEvent);
This is explained in my [Challenges](https://github.com/riftgarret/ludum/wiki/condition-challenges) section. I think maybe we could pick a solution whether we ignore it, or throw an exception or just secretly print it to log hoping that the case where this was used was intentional.

2018-11-01 02:07 UTC, RiceGnat commented on Redninja/Components/Conditions/EventCondition.cs
> +			ExpressionResolver resolver = new ExpressionResolver(self, target, battleModel, battleEvent);
It might be fine to just leave it, maybe throw an exception with an explanation inside whichever expression needs it. That way in case we define some invalid expression we at least can see a helpful exception instead of a random `NullReferenceException`.

2018-11-01 21:58 UTC, riftgarret commented
the TLDR of these changes are:
* **IChainableExpression / IChainnedExpression** have gone away. There is now just **ParamExpression** which means that it takes a single parameter to use.
* **IInitialExpression** has been replaced with **EnvExpression** which provides a environment variable created to allow these expressions to have access to variables that should be present.
* **IGroupExpression** is more explicit in how it turns a group -> single value
* **ValueExpression** is gone, we just use **EnvExpression** even if we are rendering just a single string or int value.

2018-11-05 18:59 UTC, RiceGnat approved these changes

2018-11-05 19:49 UTC, merged